export { default as Calendar } from './Calendar';
// export { default as ColorPicker } from './ColorPicker';
export { default as Customers } from './Customers';
export { default as Dashboard } from './Dashboard';
// export { default as Editor } from './Editor';
// export { default as EmployeeManagement } from './EmployeeManagement';
export { default as Employees } from './Employees';
export { default as Kanban } from './Kanban';
// export { default as Orders } from './Orders';
export { default as Projects } from './Projects'; 